"use client";

import { useState } from "react";
import { useMutation } from "convex/react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { api } from "../../convex/_generated/api";
import type { Id } from "../../convex/_generated/dataModel";

type Gesture = {
  title: string;
  rationale: string;
  estCostHkd: number;
  availability: string;
  status: string;
};

export function DelightModal({
  open,
  onOpenChange,
  guestName,
  briefId,
  gestures,
  generatedAtIso,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  guestName: string;
  briefId: Id<"briefs">;
  gestures: Gesture[];
  generatedAtIso: string;
}) {
  const approve = useMutation(api.briefs.approveGesture);
  const [busy, setBusy] = useState<number | null>(null);

  async function onApprove(index: number) {
    setBusy(index);
    try {
      await approve({ briefId, gestureIndex: index });
    } finally {
      setBusy(null);
    }
  }

  const formattedDate = new Date(generatedAtIso).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="bg-[var(--elevated)] border-[var(--border)] text-[var(--text-primary)] sm:max-w-[640px]">
        <DialogHeader className="space-y-1">
          <div className="section-label">Delight Options</div>
          <DialogTitle
            className="font-display"
            style={{ fontSize: "1.5rem", fontWeight: 500 }}
          >
            {guestName}
          </DialogTitle>
        </DialogHeader>

        <div className="flex flex-col gap-4 mt-2">
          {gestures.map((g, i) => {
            const scheduled = g.status === "scheduled";
            const primary = i === 0;
            return (
              <Card
                key={i}
                className={`p-5 gap-3 ${
                  primary
                    ? "border-l-2 border-l-[var(--accent)]"
                    : ""
                }`}
              >
                <div className="flex items-center gap-2">
                  {primary ? (
                    <span
                      className="inline-block size-1.5 rounded-full"
                      style={{ background: "var(--accent)" }}
                    />
                  ) : null}
                  <div
                    className="font-display"
                    style={{ fontSize: "1.25rem", fontWeight: 500 }}
                  >
                    {g.title}
                  </div>
                </div>
                <p className="text-[var(--text-secondary)]">{g.rationale}</p>
                <div className="flex justify-between items-center mt-1">
                  <div className="font-mono text-[0.8125rem] text-[var(--text-tertiary)]">
                    Est. HKD {g.estCostHkd.toLocaleString()} - {g.availability}
                  </div>
                  {scheduled ? (
                    <Badge
                      className="font-mono text-xs px-3 py-1.5 rounded-md"
                      style={{
                        background: "var(--accent-muted)",
                        color: "var(--accent)",
                      }}
                    >
                      Scheduled
                    </Badge>
                  ) : (
                    <Button
                      size="sm"
                      onClick={() => onApprove(i)}
                      disabled={busy === i}
                      className="font-mono text-[0.8125rem] h-auto py-2 px-3.5 border-0"
                      style={{
                        background: "var(--accent)",
                        color: "#0a0909",
                      }}
                    >
                      {busy === i ? "Scheduling..." : "Approve and Schedule"}
                    </Button>
                  )}
                </div>
              </Card>
            );
          })}
        </div>

        <div className="font-mono text-xs text-[var(--text-tertiary)] mt-2 text-right">
          Generated by Sense Pre-Arrival Agent - {formattedDate}
        </div>
      </DialogContent>
    </Dialog>
  );
}
